import { describe, it, expect } from "vitest";
import { detectBridges, roadCrossesWater } from "./bridgeDetection";
import type { Road, TerrainData, WaterFeature, RiverFeature } from "./types";

/**
 * Tests for bridge detection (CITY-148).
 */

describe("detectBridges", () => {
  it("returns empty bridges when no roads provided", () => {
    const result = detectBridges([], null);
    expect(result.bridges).toEqual([]);
    expect(result.bridgeCountByDistrict.size).toBe(0);
  });

  it("returns empty bridges when no terrain data provided", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "arterial",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 100, y: 50 },
          ],
        },
      },
    ];
    const result = detectBridges(roads, null);
    expect(result.bridges).toEqual([]);
  });

  it("returns empty bridges when terrain has no water", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "arterial",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 100, y: 50 },
          ],
        },
      },
    ];
    const terrain: TerrainData = {
      water: [],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };
    const result = detectBridges(roads, terrain);
    expect(result.bridges).toEqual([]);
  });

  it("detects bridge when road crosses water polygon", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "arterial",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 100, y: 50 },
          ],
        },
      },
    ];
    const water: WaterFeature = {
      id: "lake-1",
      type: "lake",
      polygon: {
        points: [
          { x: 40, y: 0 },
          { x: 60, y: 0 },
          { x: 60, y: 100 },
          { x: 40, y: 100 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [water],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };

    const result = detectBridges(roads, terrain);
    expect(result.bridges.length).toBe(1);
    expect(result.bridges[0].roadId).toBe("road-1");
    expect(result.bridges[0].waterType).toBe("lake");
    expect(result.bridges[0].waterFeatureId).toBe("lake-1");
    expect(result.bridges[0].autoGenerated).toBe(true);
  });

  it("detects bridge when road crosses river", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "arterial",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 100, y: 50 },
          ],
        },
      },
    ];
    const river: RiverFeature = {
      id: "river-1",
      width: 10,
      line: {
        points: [
          { x: 50, y: 0 },
          { x: 50, y: 100 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [],
      coastlines: [],
      rivers: [river],
      contours: [],
      beaches: [],
    };

    const result = detectBridges(roads, terrain);
    expect(result.bridges.length).toBe(1);
    expect(result.bridges[0].roadId).toBe("road-1");
    expect(result.bridges[0].waterType).toBe("river");
    expect(result.bridges[0].waterFeatureId).toBe("river-1");
  });

  it("does not create bridge for short crossings below minimum length", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "local",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 100, y: 50 },
          ],
        },
      },
    ];
    // Very narrow water feature (2 units wide, below default minimum of 5)
    const water: WaterFeature = {
      id: "creek-1",
      type: "lake",
      polygon: {
        points: [
          { x: 49, y: 0 },
          { x: 51, y: 0 },
          { x: 51, y: 100 },
          { x: 49, y: 100 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [water],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };

    const result = detectBridges(roads, terrain, { minBridgeLength: 5 });
    expect(result.bridges.length).toBe(0);
  });

  it("creates multiple bridges for road crossing multiple water features", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "highway",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 200, y: 50 },
          ],
        },
      },
    ];
    const terrain: TerrainData = {
      water: [
        {
          id: "lake-1",
          type: "lake",
          polygon: {
            points: [
              { x: 40, y: 0 },
              { x: 60, y: 0 },
              { x: 60, y: 100 },
              { x: 40, y: 100 },
            ],
          },
        },
        {
          id: "lake-2",
          type: "lake",
          polygon: {
            points: [
              { x: 140, y: 0 },
              { x: 160, y: 0 },
              { x: 160, y: 100 },
              { x: 140, y: 100 },
            ],
          },
        },
      ],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };

    const result = detectBridges(roads, terrain);
    expect(result.bridges.length).toBe(2);
    expect(result.bridges.map((b) => b.waterFeatureId).sort()).toEqual([
      "lake-1",
      "lake-2",
    ]);
  });

  it("does not create bridge when road does not cross water", () => {
    const roads: Road[] = [
      {
        id: "road-1",
        roadClass: "arterial",
        line: {
          points: [
            { x: 0, y: 50 },
            { x: 30, y: 50 }, // Ends before the water
          ],
        },
      },
    ];
    const water: WaterFeature = {
      id: "lake-1",
      type: "lake",
      polygon: {
        points: [
          { x: 40, y: 0 },
          { x: 60, y: 0 },
          { x: 60, y: 100 },
          { x: 40, y: 100 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [water],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };

    const result = detectBridges(roads, terrain);
    expect(result.bridges.length).toBe(0);
  });
});

describe("roadCrossesWater", () => {
  it("returns false when no terrain data", () => {
    const road: Road = {
      id: "road-1",
      roadClass: "arterial",
      line: {
        points: [
          { x: 0, y: 50 },
          { x: 100, y: 50 },
        ],
      },
    };
    expect(roadCrossesWater(road, null)).toBe(false);
  });

  it("returns false when road does not cross water", () => {
    const road: Road = {
      id: "road-1",
      roadClass: "arterial",
      line: {
        points: [
          { x: 0, y: 50 },
          { x: 30, y: 50 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [
        {
          id: "lake-1",
          type: "lake",
          polygon: {
            points: [
              { x: 40, y: 0 },
              { x: 60, y: 0 },
              { x: 60, y: 100 },
              { x: 40, y: 100 },
            ],
          },
        },
      ],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };
    expect(roadCrossesWater(road, terrain)).toBe(false);
  });

  it("returns true when road crosses water polygon", () => {
    const road: Road = {
      id: "road-1",
      roadClass: "arterial",
      line: {
        points: [
          { x: 0, y: 50 },
          { x: 100, y: 50 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [
        {
          id: "lake-1",
          type: "lake",
          polygon: {
            points: [
              { x: 40, y: 0 },
              { x: 60, y: 0 },
              { x: 60, y: 100 },
              { x: 40, y: 100 },
            ],
          },
        },
      ],
      coastlines: [],
      rivers: [],
      contours: [],
      beaches: [],
    };
    expect(roadCrossesWater(road, terrain)).toBe(true);
  });

  it("returns true when road crosses river", () => {
    const road: Road = {
      id: "road-1",
      roadClass: "arterial",
      line: {
        points: [
          { x: 0, y: 50 },
          { x: 100, y: 50 },
        ],
      },
    };
    const terrain: TerrainData = {
      water: [],
      coastlines: [],
      rivers: [
        {
          id: "river-1",
          width: 10,
          line: {
            points: [
              { x: 50, y: 0 },
              { x: 50, y: 100 },
            ],
          },
        },
      ],
      contours: [],
      beaches: [],
    };
    expect(roadCrossesWater(road, terrain)).toBe(true);
  });
});
