/**
 * Terrain data types for map rendering.
 */

export interface Point {
  x: number;
  y: number;
}

export interface Polygon {
  points: Point[];
}

export interface Line {
  points: Point[];
  width?: number;
}

export interface WaterFeature {
  id: string;
  type: "ocean" | "lake";
  polygon: Polygon;
  /** Auto-generated or user-edited name for lakes (oceans typically don't have names) */
  name?: string;
}

export interface CoastlineFeature {
  id: string;
  line: Line;
}

export interface RiverFeature {
  id: string;
  line: Line;
  width: number; // varies along length
  /** Auto-generated or user-edited name */
  name?: string;
}

export interface ContourLine {
  id: string;
  elevation: number;
  line: Line;
}

/**
 * Beach types based on adjacent water body
 */
export type BeachType = "ocean" | "bay" | "lake" | "river";

export interface BeachFeature {
  id: string;
  /** Type of water body the beach is adjacent to */
  beachType: BeachType;
  polygon: Polygon;
  /** Average width of the beach in world units (varies based on slope) */
  width?: number;
  /** Optional name for the beach */
  name?: string;
}

export interface TerrainData {
  water: WaterFeature[];
  coastlines: CoastlineFeature[];
  rivers: RiverFeature[];
  contours: ContourLine[];
  beaches: BeachFeature[];
}

// District types matching the spec
export type DistrictType =
  | "residential"
  | "downtown"
  | "commercial"
  | "industrial"
  | "hospital"
  | "university"
  | "k12"
  | "park"
  | "airport";

/**
 * Personality settings for a district.
 * Each slider is 0.0-1.0, affecting how the district generates and grows.
 * Era year determines the architectural period.
 */
export interface DistrictPersonality {
  /** 0 = strict grid, 1 = fully organic street layout */
  grid_organic: number;
  /** 0 = sprawling suburbs, 1 = dense urban core */
  sprawl_compact: number;
  /** 0 = transit-oriented, 1 = car-dependent */
  transit_car: number;
  /**
   * The architectural era year for this district.
   * Replaces the 0-1 historic_modern slider.
   * Values: 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1850, 1875, 1900, 1920, 1940, 1960, 1980, 2024 (Present)
   */
  era_year: number;
  /**
   * Block density on a 0-10 scale.
   * Affects block size per formula: actual_size = base_size * (1.5 - density/10)
   * 0 = sparse (rural, large lots), 10 = dense (urban core, small blocks)
   */
  density?: number;
}

/** Default personality values (balanced/neutral, Contemporary era) */
export const DEFAULT_DISTRICT_PERSONALITY: DistrictPersonality = {
  grid_organic: 0.5,
  sprawl_compact: 0.5,
  transit_car: 0.5,
  era_year: 2024, // Contemporary/Present
  density: 5, // Medium density
};

/**
 * Default density values by district type (0-10 scale).
 * Used when a district doesn't have an explicit density override.
 */
export const DEFAULT_DENSITY_BY_TYPE: Record<DistrictType, number> = {
  residential: 3, // Low-medium residential
  downtown: 8, // Dense urban core
  commercial: 6, // Moderate commercial
  industrial: 3, // Sparse industrial
  hospital: 5, // Medium density campus
  university: 4, // Campus with green space
  k12: 4, // School campus
  park: 1, // Very sparse (mostly open space)
  airport: 2, // Sparse infrastructure
};

export interface District {
  id: string;
  type: DistrictType;
  name: string;
  polygon: Polygon;
  isHistoric?: boolean;
  /** Per-district personality settings */
  personality?: DistrictPersonality;
}

// Road hierarchy classes
export type RoadClass =
  | "highway"
  | "arterial"
  | "collector"
  | "local"
  | "trail";

export interface Road {
  id: string;
  name?: string;
  roadClass: RoadClass;
  line: Line;
}

/**
 * Type of water feature a bridge crosses
 */
export type WaterCrossingType = "ocean" | "lake" | "river" | "bay";

/**
 * A bridge segment where a road crosses water.
 * Bridges are auto-generated when roads cross water features.
 */
export interface Bridge {
  id: string;
  /** ID of the road this bridge is part of */
  roadId: string;
  /** Type of water being crossed */
  waterType: WaterCrossingType;
  /** ID of the water feature being crossed (if available) */
  waterFeatureId?: string;
  /** Start point of the bridge (where road enters water) */
  startPoint: Point;
  /** End point of the bridge (where road exits water) */
  endPoint: Point;
  /** Length of the bridge crossing in world units */
  length: number;
  /** Whether this bridge was auto-generated or manually placed */
  autoGenerated: boolean;
}

// POI types
export type POIType =
  | "hospital"
  | "school"
  | "university"
  | "park"
  | "transit"
  | "shopping"
  | "civic"
  | "industrial";

export interface POI {
  id: string;
  name: string;
  type: POIType;
  position: Point;
}

export interface Neighborhood {
  id: string;
  name: string;
  polygon: Polygon;
  labelColor?: string;
  accentColor?: string;
}

export interface FeaturesData {
  districts: District[];
  roads: Road[];
  pois: POI[];
  neighborhoods: Neighborhood[];
  /** Bridges where roads cross water features (auto-generated) */
  bridges: Bridge[];
}

// Label types
export type LabelType =
  | "district"
  | "water"
  | "road"
  | "poi"
  | "region"
  | "contour";

export interface LabelData {
  id: string;
  text: string;
  type: LabelType;
  position: Point;
  anchor?: Point; // For curved/angled labels
  rotation?: number; // Radians
  fontSize?: number;
  priority?: number; // Higher = more important, shown first
  bounds?: { width: number; height: number }; // For collision detection
}

export interface LabelConfig {
  fontFamily: string;
  baseFontSize: number;
  color: number;
  outlineColor: number;
  outlineWidth: number;
  maxRotation: number; // Max random rotation for organic feel
  jitterAmount: number; // Random position offset
}

export interface LabelLayerData {
  labels: LabelData[];
  seed: number; // For deterministic randomness
}

export interface LayerVisibility {
  water: boolean;
  beaches: boolean;
  coastlines: boolean;
  rivers: boolean;
  contours: boolean;
  neighborhoods: boolean;
  districts: boolean;
  roads: boolean;
  bridges: boolean;
  pois: boolean;
  grid: boolean;
  labels: boolean;
  subwayTunnels: boolean;
}

export const DEFAULT_LAYER_VISIBILITY: LayerVisibility = {
  water: true,
  beaches: true,
  coastlines: true,
  rivers: true,
  contours: false,
  neighborhoods: true,
  districts: true,
  roads: true,
  bridges: true,
  pois: true,
  grid: true,
  labels: true,
  subwayTunnels: false,
};
